#!/bin/sh
set -e

# Create cm system user and group if they don't exist.
if ! getent group cm >/dev/null 2>&1; then
    groupadd --system cm
fi
if ! getent passwd cm >/dev/null 2>&1; then
    useradd --system --gid cm --home-dir /var/lib/cm --shell /usr/sbin/nologin cm
fi

# Create required directories.
mkdir -p /var/log/cm /var/lib/cm /etc/cm
chown cm:cm /var/log/cm /var/lib/cm
chmod 750 /var/log/cm /var/lib/cm

case "$1" in
    configure)
        # Only run systemctl when systemd is the init system.
        if [ -d /run/systemd/system ]; then
            # Detect constrained platforms where the cm user cannot read
            # /dev/urandom (e.g., UCK Gen1 with kernel 3.10 device cgroup
            # restrictions). On such systems, create a systemd drop-in to
            # run as root instead. Uses a dedicated filename to avoid
            # clobbering user overrides in override.conf.
            DROPIN_DIR="/etc/systemd/system/cm.service.d"
            DROPIN_FILE="${DROPIN_DIR}/50-urandom-workaround.conf"
            if [ -c /dev/urandom ] && ! su -s /bin/sh -c 'head -c1 /dev/urandom >/dev/null 2>&1' cm 2>/dev/null; then
                echo "Detected restricted /dev/urandom access for cm user."
                echo "Creating systemd drop-in to run as root."
                mkdir -p "${DROPIN_DIR}"
                cat > "${DROPIN_FILE}" << 'DROPIN'
# Auto-generated by cm postinst — platform lacks /dev/urandom access for
# non-root service users (old kernel device cgroup restriction).
# Remove this file to revert to running as the cm user.
[Service]
User=root
Group=root
DROPIN
            elif [ -f "${DROPIN_FILE}" ]; then
                # Platform issue resolved (e.g., kernel upgrade) — remove
                # the workaround so the service returns to the cm user.
                echo "Platform /dev/urandom restriction resolved. Removing root workaround."
                rm -f "${DROPIN_FILE}"
                rmdir "${DROPIN_DIR}" 2>/dev/null || true
                # Fix ownership of files created while running as root.
                chown -R cm:cm /var/log/cm /var/lib/cm 2>/dev/null || true
            fi

            systemctl daemon-reload || true
            if [ -z "$2" ]; then
                # Fresh install: enable and start.
                systemctl enable cm || true
                if systemctl start cm; then
                    echo "Config Manager installed and started."
                else
                    echo "Config Manager installed but failed to start. Check: journalctl -u cm"
                fi
            else
                # Upgrade: restart to load new binary.
                systemctl try-restart cm || true
            fi
        fi
        ;;
esac
